planner/urls.py
from django.urls import path

from planner.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    toggle_task_complete,
)


urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/toggle/", toggle_task_complete, name="task-toggle"),
    path("tag/", TagListView.as_view(), name="tag-list"),
    path("tag/create/", TagCreateView.as_view(), name="tag-create"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "planner"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("planner.urls", namespace="planner")),
]

planner/models.py
from django.db import models


class Task(models.Model):
    content = models.CharField(max_length=100)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField()
    tags = models.ManyToManyField("Tag", related_name="tasks")

    def __str__(self) -> str:
        return f"{self.content}. Is completed: {self.is_completed}."


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name

planner/forms.py
from django import forms

from planner.models import Task, Tag


class TaskCreationForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        widget=forms.SelectDateWidget,
        required=False
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Task
        fields = "__all__"

planner/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from planner.forms import TaskCreationForm
from planner.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")
    ordering = ["is_completed", "-datetime"]


class TaskCreateView(generic.CreateView):
    model = Task
    success_url = reverse_lazy("planner:index")
    form_class = TaskCreationForm


class TaskUpdateView(generic.UpdateView):
    model = Task
    success_url = reverse_lazy("planner:index")
    form_class = TaskCreationForm


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("planner:index")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    success_url = reverse_lazy("planner:tag-list")
    fields = "__all__"


class TagUpdateView(generic.UpdateView):
    model = Tag
    success_url = reverse_lazy("planner:tag-list")
    fields = "__all__"


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("planner:tag-list")


def toggle_task_complete(request: HttpRequest, pk: int) -> HttpResponse:
    task = Task.objects.get(id=pk)
    task.is_completed = not task.is_completed
    task.save()
    return HttpResponseRedirect(reverse_lazy("planner:index"))

templates/includes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    {% load static %}
</head>

<body>
<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'planner:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'planner:tag-list' %}">Tags</a></li>
</ul>

templates/planner/tag_confirm_delete.html
{% extends "includes/base.html" %}
{% block content %}
  <h1>Delete tag</h1>
  <p>Are you sure you want to delete {{ tag.name }}</p>
  <form action="" method="post">
    {% csrf_token %}
    <a class="btn btn-default" href="{% url "planner:tag-list" %}">Get back</a>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/planner/tag_form.html
{% extends "includes/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success" value="Submit">
  </form>
{% endblock %}

templates/planner/tag_list.html
{% extends "includes/base.html" %}
{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>Tags</h1>
    <a class="btn btn-primary" href="{% url "planner:tag-create" %}">Add Tag</a>
  </div>
  <table class="table table-hover mt-3">
      <thead>
        <tr>
          <th class="border-gray-200">Name</th>
          <th class="border-gray-200">Update</th>
          <th class="border-gray-200">Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for tag in tag_list %}
          <tr>
            <td>
              <span class="fw-normal">{{ tag.name }}</span>
            </td>
            <td>
              <a href="{% url "planner:tag-update" tag.id %}">Update</a>
            </td>
            <td>
              <a href="{% url "planner:tag-delete" tag.id %}">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}

templates/planner/task_confirm_delete.html
{% extends "includes/base.html" %}
{% block content %}
  <h1>Delete task</h1>
  <p>Are you sure you want to delete {{ task.content }}</p>
  <form action="" method="post">
    {% csrf_token %}
    <a class="btn btn-default" href="{% url "planner:index" %}">Get back</a>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/planner/task_form.html
{% extends "includes/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success" value="Submit">
  </form>
{% endblock %}

templates/planner/task_list.html
{% extends "includes/base.html" %}
{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>TODO list</h1>
    <a class="btn btn-primary" href="{% url "planner:task-create" %}">Add Task</a>
  </div>
  {% for task in task_list %}
    <div class="mt-3">
      <div class="d-flex justify-content-between align-items-center">
        <div class="row m-0">
          <h4 class="mb-0 mr-3">{{ task.content }} </h4>
          {% if task.is_completed %}
              <h4 style="color: green;">Done</h4>
        </div>
              <a class="btn btn-info" href="{% url "planner:task-toggle" task.id %}">Undo</a>
              {% else %}
                <h4 style="color: red;">Not done</h4>
        </div>
                <a class="btn btn-success" href="{% url "planner:task-toggle" task.id %}">Complete</a>
            {% endif %}
      </div>
      <div class="mt-3">
        <p><b>Created: </b>{{ task.datetime }}</p>
      </div>
      {% if task.deadline %}
        <div class="mt-3">
          <p><b>Deadline: </b>{{ task.deadline }}</p>
        </div>
      {% endif %}
      <div class="mt-3">
        <p class="font-weight-bold mb-1">Tags:</p>
        <div class="d-inline-block">
          {% for tag in task.tags.all %}
              <span class="badge badge-info mr-1">{{ tag.name }}</span>
            {% empty %}
            No tags
          {% endfor %}
        </div>
      </div>
      <div class="mt-2">
        <a href="{% url "planner:task-update" task.id %}">Update</a>
        <a href="{% url "planner:task-delete" task.id %}">Delete</a>
      </div>
    </div>
    <hr>
    {% empty %}
    No tasks were added
  {% endfor %}
{% endblock %}